defaults:
    - analyze_latent

batch_size: 128

# feature_names:
#   - drugs_20
#   - metagenomics_174
#   - proteomics_195

model:
  num_hidden:
    - 2368
  num_latent: 128

training_loop:
  lr: 1e-4
  num_epochs: 100
  early_stopping: true
  patience: 10